#define TTS_CSH 251 //测试.mp3
#define TTS_WZ 1 //我在
#define TTS_KTYDK 2 //空调已打开
#define TTS_KTYGB 3 //空调已关闭
#define TTS_WDYTG 4 //温度已调高
#define TTS_WDYTD 5 //温度已调低
#define TTS_HDMSHYSHWZHL 6 //好的，模式已设为制冷
#define TTS_HDMSHYSHWCHSH 7 //好的，模式已设为除湿
#define TTS_HDMSHYSHWSF 8 //好的，模式已设为送风
#define TTS_HDMSHYSHWTF 9 //好的，模式已设为通风
#define TTS_HDMSHYSHWZHR 10 //好的，模式已设为制热
#define TTS_HDMSHYSHWJR 11 //好的，模式已设为加热
#define TTS_FSDWYSHWG 12 //风速档位已设为高
#define TTS_FSDWYSHWZH 13 //风速档位已设为中
#define TTS_FSDWYSHWD 14 //风速档位已设为低
#define TTS_FSYTD 15 //风速已调大
#define TTS_FSMSHYSHWQL 16 //风速模式已设为强力
#define TTS_FSYSHWZD 17 //风速已设为最大
#define TTS_FSYJD 18 //风速已降低
#define TTS_FSMSHYSHWJY 19 //风速模式已设为静音
#define TTS_FSYSHWZX 20 //风速已设为最小
#define TTS_FSMSHYSHWZD 21 //风速模式已设为自动
#define TTS_ZYFXBFYDK 22 //左右方向摆风已打开
#define TTS_ZYFXBFYKQ 23 //左右方向摆风已开启
#define TTS_ZYFXSFYDK 24 //左右方向扫风已打开
#define TTS_ZYFXBFYGB 25 //左右方向摆风已关闭
#define TTS_ZYFXBFYTZH 26 //左右方向摆风已停止
#define TTS_ZYFXSFYGB 27 //左右方向扫风已关闭
#define TTS_ZYFXSFYTZH 28 //左右方向扫风已停止
#define TTS_SHXFXBFYDK 29 //上下方向摆风已打开
#define TTS_SHXFXBFYKQ 30 //上下方向摆风已开启
#define TTS_SHXFXBFYGB 31 //上下方向摆风已关闭
#define TTS_SHXFXBFYTZH 32 //上下方向摆风已停止
#define TTS_SFYDK 33 //扫风已打开
#define TTS_BFYDK 34 //摆风已打开
#define TTS_BFYGB 35 //摆风已关闭
#define TTS_BFYTZH 36 //摆风已停止
#define TTS_SFYGB 37 //扫风已关闭
#define TTS_HDMSHYSHZHWSHM 38 //好的，模式已设置为睡眠
#define TTS_SHMMSHYGB 39 //睡眠模式已关闭
#define TTS_YLYZD 40 //音量已增大
#define TTS_YLYJX 41 //音量已减小
#define TTS_YYHFYGBNBHTDWSHHL 42 //语音回复已关闭，你不会听到我说话了
#define TTS_JSHYDK 43 //加湿已打开
#define TTS_JSHYTZH 44 //加湿已停止
#define TTS_JSHYGB 45 //加湿已关闭
#define TTS_PXYDK 46 //屏显已打开
#define TTS_PXYGB 47 //屏显已关闭
#define TTS_JNYDK 48 //节能已打开
#define TTS_JNYGB 49 //节能已关闭
#define TTS_YYHFYDK 50 //语音回复已打开
#define TTS_QJYDK 51 //清洁已打开
#define TTS_WDYTDZG 52 //温度已调到最高
#define TTS_WDYTDZD 53 //温度已调到最低
#define TTS_HDMSHYSHWJSH 54 //好的，模式已设为加湿
#define TTS_SYKTYGB 55 //所有空调已关闭
#define TTS_HDY 1 //好的呀